-- 011_tokens_table.sql
-- Drop old auth tables, create a single tokens table.
-- owner_id and expires_at are generated by the DB — callers only insert the token.

DROP TABLE IF EXISTS auth_tokens;

CREATE TABLE tokens (
    token      VARCHAR(64) PRIMARY KEY,
    owner_id   UUID        NOT NULL DEFAULT gen_random_uuid(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '30 days'
);