apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
stringData:
  POSTGRES_USER: "platafyi"
  POSTGRES_PASSWORD: "f3f01968676b381337aa93424587bdd509778414e15a652af063748c6d3e5929"
  POSTGRES_DB: "platafyi"
